+incdir+code/accelerator/cpu_core
+incdir+code/accelerator/cpu_core/zicsr
+incdir+code/accelerator/cpu_core/support_modules
+incdir+code/accelerator/cpu_core/pipeline_registers
+incdir+code/accelerator/cpu_core/pipeline_flush_unit
+incdir+code/accelerator/cpu_core/instruction_memory
+incdir+code/accelerator/cpu_core/immediate_select_unit
+incdir+code/accelerator/cpu_core/immediate_generation_unit
+incdir+code/accelerator/cpu_core/hazard_detection_unit
+incdir+code/accelerator/cpu_core/fpu
+incdir+code/accelerator/cpu_core/forwarding_units
+incdir+code/accelerator/cpu_core/f_reg_file
+incdir+code/accelerator/cpu_core/f_alu
+incdir+code/accelerator/cpu_core/debug/seven_segment
+incdir+code/accelerator/cpu_core/debug/clock_divider
+incdir+code/accelerator/cpu_core/cpu
+incdir+code/accelerator/cpu_core/control_unit
+incdir+code/accelerator/cpu_core/branch_control_unit
+incdir+code/accelerator/cpu_core/alu
+incdir+code/accelerator/cpu_core/reg_file
+incdir+code/accelerator/router
+incdir+code/accelerator/network_interface
+incdir+code/accelerator/mesh
code/accelerator/mesh/mesh_tb.v
