// Include paths for VCS compilation
+incdir+../../accelerator/cpu_core/alu
+incdir+../../accelerator/cpu_core/branch_control_unit
+incdir+../../accelerator/cpu_core/control_unit
+incdir+../../accelerator/cpu_core/cpu
+incdir+../../accelerator/cpu_core/data_memory
+incdir+../../accelerator/cpu_core/debug/seven_segment
+incdir+../../accelerator/cpu_core/debug/clock_divider
+incdir+../../accelerator/cpu_core/f_alu
+incdir+../../accelerator/cpu_core/f_reg_file
+incdir+../../accelerator/cpu_core/forwarding_units
+incdir+../../accelerator/cpu_core/fpu
+incdir+../../accelerator/cpu_core
+incdir+../../accelerator/cpu_core/hazard_detection_unit
+incdir+../../accelerator/cpu_core/immediate_generation_unit
+incdir+../../accelerator/cpu_core/immediate_select_unit
+incdir+../../accelerator/cpu_core/instruction_memory
+incdir+../../accelerator/cpu_core/pipeline_flush_unit
+incdir+../../accelerator/cpu_core/pipeline_registers
+incdir+../../accelerator/cpu_core/reg_file
+incdir+../../accelerator/cpu_core/support_modules
+incdir+../../accelerator/cpu_core/zicsr
+incdir+../../accelerator/router
+incdir+../../accelerator/network_interface
+incdir+../../accelerator/neuron_bank
+incdir+../../accelerator/neuron_core
+incdir+../../accelerator/node
+incdir+../../accelerator/mesh
